<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="lucifer-Lenovo-E41-15" failures="2" tests="27" name="Default test" time="219.497" errors="0" timestamp="2020-12-04T11:18:24 IST">
  <testcase classname="test.UserLogInTest" name="LogInCheckFailed_01" time="3.981"/>
  <testcase classname="test.UserLogInTest" name="LogInCheckFailed_02" time="2.967"/>
  <testcase classname="test.UserLogInTest" name="LogInCheckFailed_03" time="2.895"/>
  <testcase classname="test.UserLogInTest" name="LogInCheck_01" time="4.182"/>
  <testcase classname="test.UserLogInTest" name="LogInCheck_02" time="3.934"/>
  <testcase classname="test.UserLogInTest" name="LogInCheck_03" time="3.858"/>
  <testcase classname="test.CustomerBankingTest" name="verifyDeposite" time="2.763"/>
  <testcase classname="test.CustomerBankingTest" name="verifyMoneyTransfer" time="12.093"/>
  <testcase classname="test.CustomerBankingTest" name="verifyWithdraw_01" time="1.608">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;Withdrawal&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: "Withdrawal"
at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
at java.base/java.lang.Double.parseDouble(Double.java:543)
at test.CustomerBankingTest.checkBalance(CustomerBankingTest.java:123)
at test.CustomerBankingTest.withdraw(CustomerBankingTest.java:137)
at test.CustomerBankingTest.verifyWithdraw_01(CustomerBankingTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyWithdraw_01 -->
  <testcase classname="test.CustomerBankingTest" name="verifyWithdraw_02" time="2.023">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at test.CustomerBankingTest.withdraw(CustomerBankingTest.java:139)
at test.CustomerBankingTest.verifyWithdraw_02(CustomerBankingTest.java:68)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyWithdraw_02 -->
  <testcase classname="test.HomePageTest" name="checkFooter" time="0.591"/>
  <testcase classname="test.HomePageTest" name="checkLoginPresent" time="0.215"/>
  <testcase classname="test.HomePageTest" name="verifyHeader" time="0.273"/>
  <testcase classname="test.HomePageTest" name="verifyTitle" time="0.017"/>
  <testcase classname="test.CustomerManagementTest" name="verifySearchCustomer_01" time="0.936"/>
  <testcase classname="test.CustomerManagementTest" name="verifySearchCustomer_02" time="0.897"/>
  <testcase classname="test.CustomerManagementTest" name="verifyViewCustomer" time="0.6"/>
  <testcase classname="test.CustomerManagementTest" name="verifyAddCustomer" time="5.294"/>
  <testcase classname="test.CustomerProfileTest" name="verifyPersonalDetails" time="0.988"/>
  <testcase classname="test.CustomerProfileTest" name="checkChangePasswordPass" time="7.64"/>
  <testcase classname="test.CustomerProfileTest" name="checkChangePasswordFail" time="2.25"/>
  <testcase classname="test.AdminLogInTest" name="LogInCheckFailed_01" time="3.261"/>
  <testcase classname="test.AdminLogInTest" name="LogInCheckFailed_02" time="2.819"/>
  <testcase classname="test.AdminLogInTest" name="LogInCheckFailed_03" time="2.877"/>
  <testcase classname="test.AdminLogInTest" name="LogInCheckPass_01" time="3.103"/>
  <testcase classname="test.AdminProfileTest" name="changePasswordFailTest" time="2.234"/>
  <testcase classname="test.AdminProfileTest" name="changePasswordPassTest" time="4.6"/>
</testsuite> <!-- Default test -->
